version: "3.6"
services:
  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      SERVICES: sqs
    logging:
      driver: none
  receiver:
    build: .
    network_mode: host
    depends_on:
      - localstack
    command: "bundle exec ruby daemon.rb"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
